GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltbXkiLCJpYXQiOjE1OTgzMTAyMjksImV4cCI6MTU5ODMxMDI1OX0.fsaG6oNzmK8LEakLuEgyweS16HKGw-mqrMXtU744B0E

###

POST http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltbXkiLCJpYXQiOjE1OTgzMTAxOTZ9.UoyoR1biT72JotwKJDbJ4KjJgrr14j0VOcTkolWAu68"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltbXkiLCJpYXQiOjE1OTgzMTAxOTZ9.UoyoR1biT72JotwKJDbJ4KjJgrr14j0VOcTkolWAu68"
}

###
POST http://localhost:4000/login
Content-type: application/json

{
  "username": "Jimmy"
}